ignore:
  - "examples"
  - "libdoltlite-sys/bindgen-bindings"
  - "libdoltlite-sys/doltlite"
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
